### PR TITLE
Libraries shouldn't be proguarded on their own

### PR DESCRIPTION
**Pull request by jereksel**
They should be proguarded along with app

### CODE REVIEW

**Comment by rmtheis** [comment]
Please explain your reasoning.

**Comment by jereksel** [comment]
Sure, because libs usually (I think at most cases) are compiled along with application (and it's proguarded with it), proguard it without said app doesn't make sense - it also causes proguard file to be more compilated - you have to leave public classes/method, keeping serializable methods etc.

**Comment by rmtheis** [comment]
That's a really good point. I want to do a bit of testing on this.

**Comment by rmtheis** [comment]
https://code.google.com/p/android/issues/detail?id=52962

**Comment by rmtheis** [comment]
Thanks for the contribution! These changes were applied in commit a88da77d4e445280a22611489f6974e4a5e7bc91 and #172.

**Pull request closed without merging**
