### PR TITLE
Gradle build

### PR DESCRIPTION
**Pull request by Aaargh20318**
I added a few Gradle build scripts to build tess-two and (optionally) publish the resulting library as an AAR to a maven repository. This does *not* use the new Gradle plugin with NDK support as that doesn't seem to be working for this case yet, instead it calls the existing ndk-build.

### CODE REVIEW

**Comment by rmtheis** [comment]
Awesome. I'll check this out and merge it. I may see about merging it on a separate branch while the new Gradle plugin with NDK support in Android Studio has its kinks worked out a bit more.

**Comment by rmtheis** [comment]
I'm planning to modify this to work with the experimental Gradle plugin instead of using a separate command-line build step.

**Comment by Aaargh20318** [comment]
I tried that at first but I ran into issues with the experimental plugin, can't remember exactly what the issue was though.

**Comment by jschear** [comment]
Have either of you had luck using the experimental plugin? I'm thinking of giving it a shot this week.

**Comment by rmtheis** [comment]
@jschear Nope. I've spent some time on it but I haven't gotten it to work.

**Comment by ArjanSchouten** [comment]
@jschear I wasn't able to use it too. Think we've to wait for official support in gradle and Android Studio.

**Comment by jschear** [comment]
Ah, too bad. Thanks!

**Comment by rmtheis** [comment]
If you want to give it a shot, by all means, have at it. Give me a holler on email if I can help with anything.

**Pull request merged**
