### PR TITLE
add header files explicitly so "gradlew assemble" could finish

### PR DESCRIPTION
**Pull request by ivankolev**
(cherry picked from commit b4066f1)

### CODE REVIEW

**Comment by ivankolev** [comment]
I am interested in helping with making tess-two work with tesseract 4. For now I am just sensing my way around the project, poking at the tests and whatnot. Any pointers for the uninitiated?

**Comment by JavadBadirkhanli** [comment]
Did you tested it? And, is this working on tesseract4 branch with tess 4 data ?

**Comment by rmtheis** [comment]
Not really -- have at it. If you discover anything interesting, issue #196 would a good place to comment about it.

**Comment by rmtheis** [comment]
@JavadBadirkhanli I've tested this on the master branch and it works there.

**Comment by JavadBadirkhanli** [comment]
@rmtheis I have already using master branch on my source. But i need tesseract4. And i'm waiting for it. When will you push source to this branch? ;)

**Comment by rmtheis** [comment]
@JavadBadirkhanli It is a work in progress and available on Github. See #196.

**Comment by JavadBadirkhanli** [comment]
@rmtheis yes, i'm waiting. As you see, #200  is my issue.

**Pull request merged**
